-- Contract test for the narrowly scoped Phase 2 implementation-capture
-- harness.  Runtime capture remains ROM-backed and is exercised by its shell
-- script; this test protects the deterministic, no-reference-media protocol.
local function read(path)
  local f = assert(io.open(path, "rb"))
  local text = f:read("*a")
  f:close()
  return text
end

local source = read("main.lua")
assert(source:find('POKEPORT_CAPTURE_SURFACE', 1, true))
assert(source:find('love.graphics.newCanvas(240, 160)', 1, true))
assert(source:find('love.graphics.setCanvas(world.phase2CaptureCanvas)', 1, true))
assert(source:find('love.graphics.draw(world.phase2CaptureCanvas, 0, 0)', 1, true))
assert(source:find('love.graphics.captureScreenshot(function(imageData)', 1, true))
assert(source:find('if width ~= 240 or height ~= 160 then', 1, true))
assert(source:find('PHASE2_CAPTURE_SURFACE PASS anchor=%s dimensions=240x160', 1, true))
assert(source:find('love.window.setMode(240, 160, { resizable=false })', 1, true))
assert(source:find('local y = captureSurface and -10 or 20', 1, true))
assert(source:find('if not captureSurface then', 1, true))
assert(source:find('if captureSurface then borderOffsetPx = BORDER_MARGIN_METATILES * 16 end', 1, true))

local script = read("scripts/phase2_oak_reference_evidence_capture.sh")
assert(script:find('expected_sha1=41cb23d8dccc8ebd7c649cd8fbb58eeace6e2fdc', 1, true))
assert(script:find('POKEPORT_OAKSCENE=1', 1, true))
assert(script:find('POKEPORT_MAP=3,0 POKEPORT_WALK=1', 1, true))
assert(script:find('POKEPORT_CAPTURE_SURFACE=1 POKEPORT_SCREENSHOT=1', 1, true))
assert(script:find('POKEPORT_EVIDENCE_ANCHOR="$anchor"', 1, true))
assert(script:find('PHASE2_CAPTURE_SURFACE PASS anchor=$anchor dimensions=240x160', 1, true))
assert(script:find('"$status" -ne 0 && "$status" -ne 1', 1, true))
assert(script:find('! -f "$expected" || "$(<"$log")" != *"$marker"*', 1, true))
assert(script:find('capture target was not fresh', 1, true))
assert(script:find('tools/pixeldiff/main.lua', 1, true))
assert(script:find('reference_input=absent', 1, true))
assert(not script:find('git add', 1, true))
assert(not script:find('reference%.png'))
assert(not script:find('POKEPORT_EVIDENCE_OUTPUT_DIR', 1, true))
assert(not script:find('${TMPDIR', 1, true))
assert(script:find('mktemp -d "/tmp/firered-recomp-phase2-${1}.XXXXXX"', 1, true))
assert(script:find('temporary capture root resolves inside repository', 1, true))

local task = read("work/tasks/phase2-oak-reference-evidence-harness.md")
assert(task:find('implementation_dimensions: 240x160', 1, true))
assert(task:find('reference_provenance:', 1, true))
assert(task:find('reference_crop:', 1, true))
assert(task:find('comparison_command:', 1, true))
assert(task:find('parity_claim: YES | NO', 1, true))
assert(task:find('never parity evidence', 1, true))
print("PASS: Phase 2 Oak/reference evidence harness contract")
