-- Verified-ROM end-to-end proof of main.lua's trainer-start seam.
package.path=package.path..";./?.lua"
local path=os.getenv("POKEPORT_ROM");if not path then print("SKIP phase4_foe_only_multimon_rom_test (set POKEPORT_ROM)");os.exit(0)end
local RI=require("import.RomImporter");local RA=require("import.RomAddresses");local Trainer=require("import.Trainer");local Species=require("import.SpeciesInfo");local Moves=require("import.BattleMove");local Types=require("import.TypeChart");local Nature=require("import.Nature");local Learn=require("import.LevelUpLearnset");local Flow=require("src.core.NewGameFlow");local Story=require("src.core.EarlyStory");local Starter=require("src.core.StarterPokemonFactory");local Rng=require("src.core.Rng")
local ok,info=RI.verify(path);assert(ok,tostring(info));local f=assert(io.open(path,"rb"));local rom=f:read("*a");f:close();local a=assert(RA["41cb23d8dccc8ebd7c649cd8fbb58eeace6e2fdc"]);love={};local App=require("main")
local species=Species.parseTable(rom,a.gSpeciesInfo,RA.COUNTS.NUM_SPECIES);local moves=Moves.parseTable(rom,a.gBattleMoves,RA.COUNTS.MOVES_COUNT);local catalog={species=species,moves=moves,typeChart=Types.parseTable(rom,a.gTypeEffectiveness),natures=Nature.parseTable(rom,a.sNatureStatTable),trainers=Trainer.parseTable(rom,a.gTrainers,RA.COUNTS.NUM_TRAINERS)}
local pass,fail=0,0;local function check(n,v)if v then pass=pass+1 else fail=fail+1;print("FAIL: "..n)end end
local s=App.GameSession.fromNewGame({playerGender=0,playerName=Flow.encodeName("RED"),rivalName=Flow.encodeName("GREEN")},{nextRandom16=function()return 1 end,generatedTrainerIdLower=2});local story=Story.new(s);s:setLocation(Story.MAP_PALLET_TOWN,12,1,"north");story:onStep(Story.MAP_PALLET_TOWN,12,1,{[0]={x=12,y=1,trigger=Story.VAR_PALLET_OAK_SCENE,index=0}});local choice=assert(story:beginStarterChoice(Story.MAP_OAKS_LAB,5)).choice
local starter=Starter.generate({species=choice.species,speciesInfo=species[choice.species],speciesName=rom:sub(a.gSpeciesNames+choice.species*11+1,a.gSpeciesNames+choice.species*11+10),learnset=Learn.resolve(rom,a.gLevelUpLearnsets,choice.species),battleMoves=moves,natures=catalog.natures,rng=Rng.new(1),trainer={id=s.state.saveBlock2.playerTrainerId,name=s.state.saveBlock2.playerName:sub(1,7),gender=0},metLocation=0});story:acceptStarter(starter,1)
App.configureTrainerBattleTest({romData=rom,romAddrs=a,catalog=catalog,session=s,rng=Rng.new(2),story={registerSeen=function()end}});local W=App.world;check("main start accepts Ben two-foe fixture",W.startTrainerBattle(89)and W.battle and W.battle.orchestrator);local b=W.battle;local e=b.controller.engine;local ev={};e.foe.hp=0;e:checkFaint("foe",ev);b.controller:_setMessages(b.controller:_eventMessages(ev),b.controller.ACTION)
check("BattleEngine has pending foe switch",e.awaitingForcedSwitch=="foe"and not e.outcome);while b.controller:message()do b.controller:advanceMessage()end;check("main controller replaces only after messages",e.awaitingForcedSwitch==nil and b.orchestrator.index==2 and e.foe.species==23);local flag=Story.TRAINER_FLAGS_START+89;check("first reward only and flag remains clear",b.orchestrator.rewarded[1]and not s:getFlag(flag));check("live player syncs before foe two",e.player.level==b.partyRecord.level and e.player.hp==b.partyRecord.hp and e.player.maxHP==b.partyRecord.maxHP);ev={};e.foe.hp=0;e:checkFaint("foe",ev);check("final faint has no early flag",e.outcome=="playerWon"and not s:getFlag(flag));W.finishTrainerBattle(b);check("final reward then flag",b.orchestrator.rewarded[2]and s:getFlag(flag))
-- Re-enter the real main start seam and force the existing player-loss branch.
s:clearFlag(flag);W.battle=nil;check("main starts a fresh loss fixture",W.startTrainerBattle(89));b=W.battle;e=b.controller.engine;e.player.hp=0;e:checkFaint("player",{});pcall(W.finishTrainerBattle,b);check("loss has no foe reward and never sets trainer flag",not b.orchestrator.rewarded[1] and not b.orchestrator.rewarded[2] and not s:getFlag(flag));print(("phase4_foe_only_multimon_rom_test: %d passed, %d failed"):format(pass,fail));os.exit(fail==0 and 0 or 1)
