-- Verified-ROM main.lua draw-settlement seam for the bounded state migration.
package.path=package.path..";./?.lua"
local path=os.getenv("POKEPORT_ROM");if not path then print("SKIP phase4_two_sided_replacement_state_rom_test (set POKEPORT_ROM)");os.exit(0)end
local RI=require("import.RomImporter");local RA=require("import.RomAddresses");local Trainer=require("import.Trainer");local Species=require("import.SpeciesInfo");local Moves=require("import.BattleMove");local Types=require("import.TypeChart");local Nature=require("import.Nature");local Learn=require("import.LevelUpLearnset");local Flow=require("src.core.NewGameFlow");local Story=require("src.core.EarlyStory");local Starter=require("src.core.StarterPokemonFactory");local Rng=require("src.core.Rng")
local ok,info=RI.verify(path);assert(ok,tostring(info));local f=assert(io.open(path,"rb"));local rom=f:read("*a");f:close();local a=assert(RA["41cb23d8dccc8ebd7c649cd8fbb58eeace6e2fdc"]);love={keyboard={isDown=function()return false end},image={newImageData=function()return{setPixel=function()end}end},graphics={newImage=function()return{setFilter=function()end}end}};local App=require("main")
local species=Species.parseTable(rom,a.gSpeciesInfo,RA.COUNTS.NUM_SPECIES);local moves=Moves.parseTable(rom,a.gBattleMoves,RA.COUNTS.MOVES_COUNT);local catalog={species=species,moves=moves,typeChart=Types.parseTable(rom,a.gTypeEffectiveness),natures=Nature.parseTable(rom,a.sNatureStatTable),trainers=Trainer.parseTable(rom,a.gTrainers,RA.COUNTS.NUM_TRAINERS)}
local pass,fail=0,0;local function check(n,v)if v then pass=pass+1 else fail=fail+1;print("FAIL: "..n)end end
local s=App.GameSession.fromNewGame({playerGender=0,playerName=Flow.encodeName("RED"),rivalName=Flow.encodeName("GREEN")},{nextRandom16=function()return 1 end,generatedTrainerIdLower=2});local story=Story.new(s);s:setLocation(Story.MAP_PALLET_TOWN,12,1,"north");story:onStep(Story.MAP_PALLET_TOWN,12,1,{[0]={x=12,y=1,trigger=Story.VAR_PALLET_OAK_SCENE,index=0}});local choice=assert(story:beginStarterChoice(Story.MAP_OAKS_LAB,5)).choice
local starter=Starter.generate({species=choice.species,speciesInfo=species[choice.species],speciesName=rom:sub(a.gSpeciesNames+choice.species*11+1,a.gSpeciesNames+choice.species*11+10),learnset=Learn.resolve(rom,a.gLevelUpLearnsets,choice.species),battleMoves=moves,natures=catalog.natures,rng=Rng.new(1),trainer={id=s.state.saveBlock2.playerTrainerId,name=s.state.saveBlock2.playerName:sub(1,7),gender=0},metLocation=0});story:acceptStarter(starter,1)
App.configureTrainerBattleTest({romData=rom,romAddrs=a,catalog=catalog,session=s,rng=Rng.new(2),story=story});local W=App.world;check("starts verified two-foe fixture",W.startTrainerBattle(89));local b=W.battle;local e=b.controller.engine;b.orchestrator.index=#b.orchestrator.foes;e.player.hp,e.foe.hp=0,0;local ev={};e:beginFaintSequence();e:recordFaint("player",ev);e:recordFaint("foe",ev);e:finalizeFaintSequence(ev)
local flag=Story.TRAINER_FLAGS_START+89;local before=s.money or s.state.saveBlock1.money;check("verified fixture produces draw terminal without pending replacement",e.outcome=="playerDrew"and e.awaitingForcedSwitch==nil);pcall(W.finishTrainerBattle,b);check("draw uses loss settlement with no trainer win/reward",not s:getFlag(flag)and not b.orchestrator.rewarded[1]and not b.orchestrator.rewarded[2]and (s.state.saveBlock1.money or 0)<=before)
-- Exercise both Oak-lab draw branches without inventing a battle result:
-- story is in real scene 3 after acceptStarter, so finish must normalize draw
-- to the existing loss completion accepted by EarlyStory.
local oak={kind="oakLabRival",trainerId=choice.rivalTrainerId,partyRecord=starter,rivalName="GREEN",settled=false,textImages={},controller={engine={outcome="playerDrew"},appendMessages=function()end}}
W.battle=oak;W.settleOakLabRivalBattle(oak);check("Oak draw uses loss settlement without error",oak.settled and not oak.settlementError);W.finishOakLabRivalBattle(oak);check("Oak draw normalizes to loss story completion",s:getVar(Story.VAR_OAKS_LAB_SCENE)==4);if s:getVar(Story.VAR_OAKS_LAB_SCENE)~=4 then print("Oak draw scene="..tostring(s:getVar(Story.VAR_OAKS_LAB_SCENE)).." id="..tostring(choice.rivalTrainerId))end
-- Drive the actual love.update wild completion branch with a draw outcome.
local wildBefore=s.state.saveBlock1.money or 0;W.battle={controller={engine={outcome="playerDrew"},processInput=function()end,isComplete=function()return true end},partyRecord=starter,persistedTurn=0,textImages={}};love.update(1/60);check("wild draw uses whiteout loss branch",W.battle==nil and (s.state.saveBlock1.money or 0)<=wildBefore)
print(("phase4_two_sided_replacement_state_rom_test: %d passed, %d failed"):format(pass,fail));os.exit(fail==0 and 0 or 1)
