-- Real default values assigned to a fresh FireRed save, transcribed
-- from pokefirered's actual new-game procedural code:
--   * src/new_game.c: SetDefaultOptions(), NewGameInitData(),
--     WarpToPlayersRoom(), ResetMiniGamesResults()
--   * src/event_data.c: InitEventData() (memsets flags/vars to 0),
--     EnableNationalPokedex_RSE() (leftover RSE call, see note below)
--   * src/player_pc.c: NewGameInitPCItems() + its real gNewGamePCItems
--     table
--   * src/overworld.c: ResetGameStats() (zeroes gameStats), SetMoney()
--     (money.c, XORed with encryptionKey)
--   * data/event_scripts.s: EventScript_ResetAllMapFlags (real script,
--     run via RunScriptImmediately() at the end of NewGameInitData())
--
-- Call chain verified: NewGameInitData() is called from
-- src/overworld.c (Overworld_ResetStateAfterFly-adjacent init path,
-- also reachable via Sav2_ClearSetDefault() -> SetDefaultOptions()
-- alone for a plain options reset without a full new game).
--
-- Every field/value below is directly transcribed from the cited
-- source; none are invented. Fields SaveBlockLayout.lua models but
-- this file has no entry for (playerName, playerGender,
-- playerTrainerId, rivalName) are NOT "defaulted" by this code path --
-- they're set by the naming/intro screens (src/oak_speech.c) or, for
-- playerTrainerId, randomly generated by InitPlayerTrainerId()
-- (`(Random() << 16) | GetGeneratedTrainerIdLower()`), so there is no
-- fixed default value to record for them.
--
-- Deliberately NOT modeled here (out of this task's scope per the
-- handoff brief): PC box contents/layout, object events, quest log,
-- mail, daycare, mystery gift, trainer tower, battle tower, berry
-- crush/pokemon jump/berry picking minigame records, easy chat
-- phrases, roamer data, external event data/flags, Fame Checker,
-- registered texts, trainer name records -- NewGameInitData() clears
-- all of these via dedicated Clear*/Reset*/Init* calls, but none of
-- them have interesting "default values" beyond "zeroed/empty", so
-- transcribing each call site wasn't worth the surface area for a
-- "new game just started" foundation.

local NewGameDefaults = {}

-- SetDefaultOptions() (src/new_game.c) -- real constant values from
-- include/constants/global.h.
NewGameDefaults.options = {
  textSpeed      = 1, -- OPTIONS_TEXT_SPEED_MID
  windowFrameType = 0,
  sound          = 0, -- OPTIONS_SOUND_MONO
  battleStyle    = 0, -- OPTIONS_BATTLE_STYLE_SHIFT
  battleSceneOff = false,
  regionMapZoom  = false,
  buttonMode     = 0, -- OPTIONS_BUTTON_MODE_HELP
}

-- Misc SaveBlock2 fields NewGameInitData() sets directly.
NewGameDefaults.saveBlock2 = {
  encryptionKey        = 0,
  specialSaveWarpFlags = 0,
  gcnLinkFlags          = 0,
  unkFlag1              = true,  -- "Set TRUE, never read" (real source comment)
  unkFlag2              = false, -- "Set FALSE, never read" (real source comment)
  -- EnableNationalPokedex_RSE() leftover RSE call -- its own source
  -- comment says "the var, struct member, and flag are never used" in
  -- FRLG. Included here because it IS real code that really runs on
  -- every new FireRed game, not because it does anything observable.
  pokedexUnused = 0xDA,
}

-- SetMoney(&gSaveBlock1Ptr->money, 3000) in NewGameInitData(). Since
-- encryptionKey is set to 0 immediately before this call, the raw
-- stored u32 equals the plain value (money.c: SetMoney XORs with
-- encryptionKey, so 3000 XOR 0 == 3000).
NewGameDefaults.startingMoney = 3000

-- WarpToPlayersRoom() (src/new_game.c): the destination the new save's
-- SaveBlock1.location gets set to (via SetWarpDestination ->
-- WarpIntoMap -> ApplyCurrentWarp, confirmed in src/overworld.c).
NewGameDefaults.startingWarp = {
  map    = "MAP_PALLET_TOWN_PLAYERS_HOUSE_2F",
  warpId = -1,
  x      = 6,
  y      = 6,
}

-- NewGameInitPCItems() (src/player_pc.c), real gNewGamePCItems table:
--   static const struct ItemSlot gNewGamePCItems[] = {
--     { ITEM_POTION, 1 },
--     { ITEM_NONE,   0 },
--   };
-- The loop stops at the first ITEM_NONE sentinel, so a fresh save's PC
-- has exactly one item: 1 Potion.
NewGameDefaults.startingPCItems = {
  { item = "ITEM_POTION", quantity = 1 },
}

-- InitEventData() (src/event_data.c) memsets SaveBlock1.flags and
-- .vars to all zero, and clears the special (0x8000+) flags array too.
-- What runs AFTER that in NewGameInitData(), overriding a few entries
-- away from zero:

-- EnableNationalPokedex_RSE() (src/event_data.c) -- real but
-- functionally dead in FRLG per its own source comment.
NewGameDefaults.setVars = {
  { var = "VAR_0x403C", value = 0x0302, note = "EnableNationalPokedex_RSE leftover, unused" },
  -- EventScript_ResetAllMapFlags (data/event_scripts.s), real setvar:
  { var = "VAR_MASSAGE_COOLDOWN_STEP_COUNTER", value = 500 },
}

NewGameDefaults.setFlags = {
  "FLAG_0x838", -- EnableNationalPokedex_RSE leftover, unused
}

-- EventScript_ResetAllMapFlags (data/event_scripts.s), verbatim list of
-- every `setflag` it runs, in source order. All 49 are real
-- FLAG_HIDE_* constants from include/constants/flags.h; this script
-- always runs as the last step of NewGameInitData(), so every one of
-- these is TRUE ("hidden"/"not yet triggered") on a freshly started
-- game.
local resetMapFlags = {
  "FLAG_HIDE_OAK_IN_HIS_LAB",
  "FLAG_HIDE_OAK_IN_PALLET_TOWN",
  "FLAG_HIDE_BILL_HUMAN_SEA_COTTAGE",
  "FLAG_HIDE_PEWTER_CITY_RUNNING_SHOES_GUY",
  "FLAG_HIDE_POKEHOUSE_FUJI",
  "FLAG_HIDE_LIFT_KEY",
  "FLAG_HIDE_SILPH_SCOPE",
  "FLAG_HIDE_CERULEAN_RIVAL",
  "FLAG_HIDE_SS_ANNE_RIVAL",
  "FLAG_HIDE_VERMILION_CITY_OAKS_AIDE",
  "FLAG_HIDE_SAFFRON_CIVILIANS",
  "FLAG_HIDE_ROUTE_22_RIVAL",
  "FLAG_HIDE_OAK_IN_CHAMP_ROOM",
  "FLAG_HIDE_CREDITS_RIVAL",
  "FLAG_HIDE_CREDITS_OAK",
  "FLAG_HIDE_CINNABAR_BILL",
  "FLAG_HIDE_CINNABAR_SEAGALLOP",
  "FLAG_HIDE_CINNABAR_POKECENTER_BILL",
  "FLAG_HIDE_LORELEI_IN_HER_HOUSE",
  "FLAG_HIDE_SAFFRON_FAN_CLUB_BLACK_BELT",
  "FLAG_HIDE_SAFFRON_FAN_CLUB_ROCKER",
  "FLAG_HIDE_SAFFRON_FAN_CLUB_WOMAN",
  "FLAG_HIDE_SAFFRON_FAN_CLUB_BEAUTY",
  "FLAG_HIDE_TWO_ISLAND_GAME_CORNER_LOSTELLE",
  "FLAG_HIDE_TWO_ISLAND_GAME_CORNER_BIKER",
  "FLAG_HIDE_TWO_ISLAND_WOMAN",
  "FLAG_HIDE_TWO_ISLAND_BEAUTY",
  "FLAG_HIDE_TWO_ISLAND_POKE_MANIAC",
  "FLAG_HIDE_LOSTELLE_IN_HER_HOME",
  "FLAG_HIDE_THREE_ISLAND_LONE_BIKER",
  "FLAG_HIDE_FOUR_ISLAND_RIVAL",
  "FLAG_HIDE_DOTTED_HOLE_SCIENTIST",
  "FLAG_HIDE_RESORT_GORGEOUS_SELPHY",
  "FLAG_HIDE_RESORT_GORGEOUS_INSIDE_SELPHY",
  "FLAG_HIDE_SELPHYS_BUTLER",
  "FLAG_HIDE_DEOXYS",
  "FLAG_HIDE_LORELEI_HOUSE_MEOWTH_DOLL",
  "FLAG_HIDE_LORELEI_HOUSE_CHANSEY_DOLL",
  "FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_F_DOLL",
  "FLAG_HIDE_LORELEI_HOUSE_JIGGLYPUFF_DOLL",
  "FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_M_DOLL",
  "FLAG_HIDE_LORELEIS_HOUSE_FEAROW_DOLL",
  "FLAG_HIDE_LORELEIS_HOUSE_PIDGEOT_DOLL",
  "FLAG_HIDE_LORELEIS_HOUSE_LAPRAS_DOLL",
  "FLAG_HIDE_POSTGAME_GOSSIPERS",
  "FLAG_HIDE_FAME_CHECKER_ERIKA_JOURNALS",
  "FLAG_HIDE_FAME_CHECKER_KOGA_JOURNAL",
  "FLAG_HIDE_FAME_CHECKER_LT_SURGE_JOURNAL",
  "FLAG_HIDE_SAFFRON_CITY_POKECENTER_SABRINA_JOURNALS",
}
for _, flag in ipairs(resetMapFlags) do
  NewGameDefaults.setFlags[#NewGameDefaults.setFlags + 1] = flag
end

-- ZeroPlayerPartyMons() / gPlayerPartyCount = 0 / ClearBag() /
-- ResetGameStats(): all real, all reduce to "zeroed", not interesting
-- default *values* -- callers should just treat SaveBlockLayout's
-- playerParty/bagPocket_*/gameStats fields as zero-filled on a new
-- game, no separate table needed for that.
NewGameDefaults.startingPartyCount = 0

return NewGameDefaults
